sadoprotocol/ordit

src/Libraries/Indexer/Indexer.ts, src/Libraries/Limiter.ts
current bottleneck when processing large transactions inside a block is await getAddressessFromVout(vout). using concurrency when processing the vout will increase performance because it will minimize I/O blocking
=> perf(handleBlock): use concurency when processing vouts

src/Methods/Transactions/GetConfirmations.ts
calling `Transactions.GetConfirmations` with a single invalid transaction will cause RPC to throw error. Ideally, this batch RPC should skip ids that are returning errors and only return those that are valid.
Added Try Catch to skip error
=> feat(transaction): skip error transaction on GetConfirmations

src/Libraries/Limiter.ts, src/Methods/Ordinals/GetInscriptionsTransactions.ts, src/Methods/Transactions/GetTransactionsInBulk.ts
1. Add `GetTransactionsInBulk` that accepts a list of `txIds` returns all transactions data.
2. Add `GetInscriptionsTransactions` that returns inscriptions data along with the outpoint tx (latest tx)
=> feat(rpc): add GetTransactionsInBulk + add GetInscriptionsTransactions

src/Database/Inscriptions/Collection.ts, src/Database/Inscriptions/Methods.ts, src/Libraries/Inscriptions/Envelope.ts, src/Libraries/Inscriptions/Inscription.ts, src/Methods/Ordinals/GetInscriptions.ts, src/Methods/Ordinals/GetInscriptionsByIds.ts, src/Methods/Ordinals/GetInscriptionsTransactions.ts, src/Services/Ord.ts, src/Workers/Indexers/Inscriptions.ts, src/Workers/Tasks/ReindexDelegateInscriptions.ts, src/Workers/Tasks/ReindexInscriptionsPointers.ts, src/Workers/Tasks/ReindexInscriptionsTx.ts
background: some witness transactions have more than one inscription (containing many inscriptions). currently, ordit only indexes the first inscription. this PR fixes the envelop function to parse multiple inscriptions in the witness transaction.
example tx: https://mempool.space/tx/c9f5ea06fbece058f66fb8171dff1c199a56f6f5f7e3007b7eb043def5c38a10
=> fix(indexer): support index multiple inscriptions in witness

src/Methods/Address/GetSpendables.ts, src/Methods/Address/GetUnspents.ts, src/Services/Bitcoin/Transactions.ts
- Change `getrawtransaction` to `gettxout`, which excludes outputs already spent or waiting to be spent in the mempool
=> fix(api): fix mempool conflict issue

src/Libraries/Inscriptions/Envelope.ts, src/Libraries/Inscriptions/Inscription.ts, src/Workers/Indexers/Inscriptions.ts
Fixes issue where the Indexer only indexes the first inscription (index 0) in a transaction
=> fix(indexer): track envelope index when parsing vins

src/Methods/Address/GetSpendables.ts, src/Methods/Address/GetUnspents.ts, src/Services/Bitcoin/Transactions.ts
- When UTXO is spent in mempool, the [`gettxout`](https://bitcoincore.org/en/doc/27.0.0/rpc/blockchain/gettxout/) RPC method returns `null` instead of `undefined`.
=> fix(api): txout returns null when utxo is spent in mempool

dotenv, src/Config.ts, src/Workers/Index.ts, src/Workers/Worker.ts
Allow for an optional `maxheight` setting to stop indexing at `maxheight`. This would make it easier to take DB snapshots at specific heights (eg. before first inscription height, before jubilee height, etc.).
=> feat(indexer): add config setting for maxheight

package.json
According to https://github.com/oven-sh/bun/issues/5835 there is not know fix/workaround. We can come back to this if the issue is resolved. Back to using tsx.
Related issue: #52
=> fix(bun): symbol lookup error

src/Libraries/Environment.ts
- Configs can be optional, but setting `optional` as `true` but not setting the variable on `.env` throws an error
- This fix returns `undefined` when an optional config is not set
=> fix(indexer): optional configs not returning undefined when not set

src/Services/Ord.ts
- Ord throws a 404 error on `/inscriptions` endpoint if just one inscription in the list is invalid
- This removes the offending inscription and retries the call
=> fix(ord): skip missing inscription

src/Libraries/Inscriptions/Envelope.ts
- Delegate parsing assumes inscription is on index 0
- This change uses the parsing function from the Parents feature to parse delegate inscription IDs
=> fix(indexer): parse delegate inscription ID

src/Database/Output/Collection.ts, src/Libraries/Runes/types.ts, src/Methods/Runes/GetSpendablesIndex.ts, src/Workers/Indexers/Outputs.ts
Implementation of Runes.GetSpendableIndex endpoint which returns all utxos that are safe to spend, meaning they contain no rune balances or inscriptions
=> feat(api): Runes.GetSpendableIndex endpoint

src/Libraries/Paginate/FindPaginated.ts, src/Methods/Runes/GetAddressRuneUTXOIndex.ts
- Added a cursorInfo flag to the findPaginated function (default true)
- $cursor is now omited from the individual documents only when cursorInfo is set to false.
- Cursors for prev and next pagination fields are always computed and returned, regardless of cursorInfo flag.
=> fix(api): add parameter to make cursor information optional on pagination

src/Fastify.ts
- Removes `X-Content-Type-Options: nosniff` from header to better support recursive inscriptions
=> fix(api): turn off X-Content-Type-Options on header for fastify helmet

dotenv, src/Config.ts, src/Libraries/Indexer/Indexer.ts
Adds INDEXER_BLOCK_CONCURRENCY_LIMIT. 
This variable will set the limit at which blocks are concurrently fetched by getBlock RPC.
=> feat(indexer) add blockConcurrencyLimit

src/Methods/Runes/GetAddressRuneUTXOIndex.ts
Runes.GetAddressRuneUTXOIndex:
- Make runeTicker optional to be able to retrieve all UTXOs with runes and balances of an address
- Added includeSpent optional param to be able to retrieve spent UTXOs conditionally. Defaults to false.
=> fix(api): make runeTicker optional and add includeSpent param

src/Database/Output/Methods.ts, src/Methods/Address/GetSpendablesPaginated.ts
Adds `GetSpendables` as `GetSpendablesPaginated` with pagination support.
Separate method needed to not break existing `GetSpendables` implementations.
Pagination changes taken from https://github.com/sadoprotocol/ordit/pull/87.
=> feature(api): added Address.GetSpendablesPaginated

dotenv, indexer_runner.sh, package-lock.json, package.json, src/Bootstrap.ts, src/Config.ts, src/Database/Runes/Collection.ts, src/Database/Runes/Methods.ts, src/Database/Runes/index.ts, src/Database/index.ts, src/Libraries/Indexer/Indexer.ts, src/Libraries/Indexer/Reorg.ts, src/Libraries/Runes/Constants.ts, src/Methods/Runes/GetAddressRuneUTXOIndex.ts, src/Methods/Runes/GetBalancesIndex.ts, src/Methods/Runes/GetRuneIndex.ts, src/Utilities/Helpers.ts, src/Utilities/Runes.ts, src/Workers/Index.ts, src/Workers/Indexers/Inscriptions.ts, src/Workers/Indexers/Outputs.ts, src/Workers/Indexers/Runes.ts, src/Workers/Worker.ts
This PR aims to have a better reorg handling logic for the indexer. 
Main changes:
- Change order of indexers:
- Reorg logic checks for collection outputs so this indexer must run last. In case of failure or reorg all other indexers will be able to get the correct reorg height and act accordingly.
- Introduced `INDEXER_START_HEIGHT` to allow indexing from a specified block height.
- Simplified and consolidated reorg logic for efficiency.
- Adjusted indexer behavior for `runesOnly` and `startHeight` settings.
- Optimized database models and improved BigInt handling.
- Refactored worker control flow and enhanced logging.
- Added indexer_runner.sh
- This script handles OOM issues and tries different configurations for the BLOCK_COMMIT_INTERVAL aiming to speed the indexing.
- Added fix for …
=> fix(indexer): better reorg handling

.gitignore, package-lock.json, package.json, src/Database/Runes/Methods.ts, src/Libraries/Indexer/Indexer.ts, src/Libraries/Indexer/Reorg.ts, src/Workers/Indexers/Runes.ts, src/Workers/Tasks/AddressBalanceValidator.ts
This PR fixes the spent outputs reorg logic.
- Since the spending of outputs updated the txBlockHeight, on reorg, the spent outputs where deleted instead of marking them as spendable again.
- Also the PR simplifies the reorg logic since the previous logic was unnecessary.
=> fix(indexer): fix bug on spent outputs reorg logic
